name = "tic-tac-toe"
version = "0.1.0"
license = "license"
author = "lukbrb"
maintainer = "lucasbarbr@outlook.com"
copyright = "Copyright 2023, lukbrb"


[build]
external-modules = ["IOKit","Cocoa","OpenGL"]